//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageManagementCore.GlobalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OperatingMethodsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperatingMethodsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageManagementCore.GlobalizationResources.OperatingMethodsStrings", typeof(OperatingMethodsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePagefileSettings_CouldntDisableManagement {
            get {
                return ResourceManager.GetString("ChangePagefileSettings_CouldntDisableManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePagefileSettings_MinGreaterMax {
            get {
                return ResourceManager.GetString("ChangePagefileSettings_MinGreaterMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePagefileSettings_Not1Pagefile {
            get {
                return ResourceManager.GetString("ChangePagefileSettings_Not1Pagefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePagefileSettings_NotEnoughSpace {
            get {
                return ResourceManager.GetString("ChangePagefileSettings_NotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePagefileSettings_SelectedPartitionMissing {
            get {
                return ResourceManager.GetString("ChangePagefileSettings_SelectedPartitionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_DeleteContent_Text {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_DeleteContent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_DeleteContent_Title {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_DeleteContent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_ErrorChangeSubfolder_Abort {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_ErrorChangeSubfolder_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_ErrorChangeSubfolder_Ignore {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_ErrorChangeSubfolder_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_ErrorChangeSubfolder_Retry {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_ErrorChangeSubfolder_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_ErrorChangeSubfolder_Skip {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_ErrorChangeSubfolder_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_ErrorChangeSubfolder_Text {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_ErrorChangeSubfolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_MoveContent_Text {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_MoveContent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_MoveContent_Title {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_MoveContent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_RestartExplorer_Text {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_RestartExplorer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_RestartExplorer_Title {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_RestartExplorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_SubfolderFound_No {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_SubfolderFound_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_SubfolderFound_Text {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_SubfolderFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_SubfolderFound_Title {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_SubfolderFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_SubfolderFound_Yes {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_SubfolderFound_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangeUserShellFolder_SubfolderFound_YesAll {
            get {
                return ResourceManager.GetString("ChangeUserShellFolder_SubfolderFound_YesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DriveType2String_CDRom {
            get {
                return ResourceManager.GetString("DriveType2String_CDRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DriveType2String_Fixed {
            get {
                return ResourceManager.GetString("DriveType2String_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DriveType2String_Network {
            get {
                return ResourceManager.GetString("DriveType2String_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DriveType2String_NoRootDirectory {
            get {
                return ResourceManager.GetString("DriveType2String_NoRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DriveType2String_RAM {
            get {
                return ResourceManager.GetString("DriveType2String_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DriveType2String_Removable {
            get {
                return ResourceManager.GetString("DriveType2String_Removable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DriveType2String_Unknown {
            get {
                return ResourceManager.GetString("DriveType2String_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetDescription_Base {
            get {
                return ResourceManager.GetString("GetDescription_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetDescription_Disabled {
            get {
                return ResourceManager.GetString("GetDescription_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetDescription_Moved {
            get {
                return ResourceManager.GetString("GetDescription_Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetDescription_MovedNoAdmin {
            get {
                return ResourceManager.GetString("GetDescription_MovedNoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetDescription_None {
            get {
                return ResourceManager.GetString("GetDescription_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetDescription_Standard {
            get {
                return ResourceManager.GetString("GetDescription_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MoveFolderOrFile_PathsEqual {
            get {
                return ResourceManager.GetString("MoveFolderOrFile_PathsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SetSearchDataPath_InvalidPath {
            get {
                return ResourceManager.GetString("SetSearchDataPath_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SetSearchDataPath_RestartNow_Title {
            get {
                return ResourceManager.GetString("SetSearchDataPath_RestartNow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SetStadium_ErrorNoneAfterLast {
            get {
                return ResourceManager.GetString("SetStadium_ErrorNoneAfterLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SetStadium_ErrorNoneBeforeFirst {
            get {
                return ResourceManager.GetString("SetStadium_ErrorNoneBeforeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SetStadium_NewInvalid {
            get {
                return ResourceManager.GetString("SetStadium_NewInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SetStadium_NoNewPathGiven {
            get {
                return ResourceManager.GetString("SetStadium_NoNewPathGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StoreOnHDDLinkName {
            get {
                return ResourceManager.GetString("StoreOnHDDLinkName", resourceCulture);
            }
        }
    }
}
