//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageManagementTool.GlobalizationRessources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserShellFolderStrings_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserShellFolderStrings_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageManagementTool.GlobalizationRessources.UserShellFolderStrings.de-DE", typeof(UserShellFolderStrings_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratorenwerkzeuge.
        /// </summary>
        public static string Administrative_Tools_Name {
            get {
                return ResourceManager.GetString("Administrative_Tools_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendungsdaten.
        /// </summary>
        public static string Appdata_Name {
            get {
                return ResourceManager.GetString("Appdata_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internetcache.
        /// </summary>
        public static string Cache_Name {
            get {
                return ResourceManager.GetString("Cache_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporäre Dateien zum CD brennen.
        /// </summary>
        public static string CD_Burning_Name {
            get {
                return ResourceManager.GetString("CD_Burning_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Anwendungsdaten.
        /// </summary>
        public static string Common_Administrative_Tools_Name {
            get {
                return ResourceManager.GetString("Common_Administrative_Tools_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Anwendungsdaten.
        /// </summary>
        public static string Common_AppData_Name {
            get {
                return ResourceManager.GetString("Common_AppData_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentlicher Desktop.
        /// </summary>
        public static string Common_Desktop_Name {
            get {
                return ResourceManager.GetString("Common_Desktop_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Dokumente.
        /// </summary>
        public static string Common_Documents_Name {
            get {
                return ResourceManager.GetString("Common_Documents_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Starmenü Programme.
        /// </summary>
        public static string Common_Programs_Name {
            get {
                return ResourceManager.GetString("Common_Programs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliches Startmenü.
        /// </summary>
        public static string Common_Start_Menu_Name {
            get {
                return ResourceManager.GetString("Common_Start_Menu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentlicher Autostart.
        /// </summary>
        public static string Common_Startup_Name {
            get {
                return ResourceManager.GetString("Common_Startup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Vorlagen.
        /// </summary>
        public static string Common_Templates_Name {
            get {
                return ResourceManager.GetString("Common_Templates_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Musik.
        /// </summary>
        public static string CommonMusic_Name {
            get {
                return ResourceManager.GetString("CommonMusic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Bilder.
        /// </summary>
        public static string CommonPictures_Name {
            get {
                return ResourceManager.GetString("CommonPictures_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Videos.
        /// </summary>
        public static string CommonVideo_Name {
            get {
                return ResourceManager.GetString("CommonVideo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string Cookies_Name {
            get {
                return ResourceManager.GetString("Cookies_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string Desktop_Name {
            get {
                return ResourceManager.GetString("Desktop_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads_Name {
            get {
                return ResourceManager.GetString("Downloads_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        public static string Favorites_Names {
            get {
                return ResourceManager.GetString("Favorites_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schriftarten.
        /// </summary>
        public static string Fonts_Name {
            get {
                return ResourceManager.GetString("Fonts_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlauf.
        /// </summary>
        public static string History_Name {
            get {
                return ResourceManager.GetString("History_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliotheken.
        /// </summary>
        public static string Libraries_Name {
            get {
                return ResourceManager.GetString("Libraries_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokale Anwendungsdaten.
        /// </summary>
        public static string Local_AppData_Name {
            get {
                return ResourceManager.GetString("Local_AppData_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Musik.
        /// </summary>
        public static string My_Music_Name {
            get {
                return ResourceManager.GetString("My_Music_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Bilder.
        /// </summary>
        public static string My_Pictures_Name {
            get {
                return ResourceManager.GetString("My_Pictures_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Videos.
        /// </summary>
        public static string My_Video_Name {
            get {
                return ResourceManager.GetString("My_Video_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzwerkverknüpfungen.
        /// </summary>
        public static string NetHood_Name {
            get {
                return ResourceManager.GetString("NetHood_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hersteller Links.
        /// </summary>
        public static string OEM_Links_Name {
            get {
                return ResourceManager.GetString("OEM_Links_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Dokumente.
        /// </summary>
        public static string Personal_Name {
            get {
                return ResourceManager.GetString("Personal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druckerverknüpfung.
        /// </summary>
        public static string PrintHood_Name {
            get {
                return ResourceManager.GetString("PrintHood_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporäre Dateien.
        /// </summary>
        public static string PrivateTemp {
            get {
                return ResourceManager.GetString("PrivateTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installationspfad für x64 basierte Programme.
        /// </summary>
        public static string ProgramFilesDir_Name {
            get {
                return ResourceManager.GetString("ProgramFilesDir_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installationspfad für x86 basierte Programme.
        /// </summary>
        public static string ProgramFilesDir_x86_Name {
            get {
                return ResourceManager.GetString("ProgramFilesDir_x86_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startmenü Programme.
        /// </summary>
        public static string Programs_Name {
            get {
                return ResourceManager.GetString("Programs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentliche Temporäre Dateien.
        /// </summary>
        public static string PublicTemp {
            get {
                return ResourceManager.GetString("PublicTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt verwendet.
        /// </summary>
        public static string Recent_Name {
            get {
                return ResourceManager.GetString("Recent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden an.
        /// </summary>
        public static string SendTo_Name {
            get {
                return ResourceManager.GetString("SendTo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startmenü.
        /// </summary>
        public static string Start_Menu_Name {
            get {
                return ResourceManager.GetString("Start_Menu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        public static string Startup_Name {
            get {
                return ResourceManager.GetString("Startup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlagen.
        /// </summary>
        public static string Templates_Name {
            get {
                return ResourceManager.GetString("Templates_Name", resourceCulture);
            }
        }
    }
}
