//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageManagementTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class EnterCredentialsDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnterCredentialsDialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageManagementTool.EnterCredentialsDialog", typeof(EnterCredentialsDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles Abort_btn_Anchor {
            get {
                object obj = ResourceManager.GetObject("Abort_btn.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=128}.
        /// </summary>
        public static System.Drawing.Point Abort_btn_Location {
            get {
                object obj = ResourceManager.GetObject("Abort_btn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=112, Height=23}.
        /// </summary>
        public static System.Drawing.Size Abort_btn_Size {
            get {
                object obj = ResourceManager.GetObject("Abort_btn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int Abort_btn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("Abort_btn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Abort_btn_Text {
            get {
                return ResourceManager.GetString("Abort_btn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Headline0_lbl_AutoSize {
            get {
                object obj = ResourceManager.GetObject("Headline0_lbl.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=13}.
        /// </summary>
        public static System.Drawing.Point Headline0_lbl_Location {
            get {
                object obj = ResourceManager.GetObject("Headline0_lbl.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=207, Height=13}.
        /// </summary>
        public static System.Drawing.Size Headline0_lbl_Size {
            get {
                object obj = ResourceManager.GetObject("Headline0_lbl.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int Headline0_lbl_TabIndex {
            get {
                object obj = ResourceManager.GetObject("Headline0_lbl.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben sie die Anmeldeinformationen  .
        /// </summary>
        public static string Headline0_lbl_Text {
            get {
                return ResourceManager.GetString("Headline0_lbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Headline1_lbl_AutoSize {
            get {
                object obj = ResourceManager.GetObject("Headline1_lbl.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=26}.
        /// </summary>
        public static System.Drawing.Point Headline1_lbl_Location {
            get {
                object obj = ResourceManager.GetObject("Headline1_lbl.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=113, Height=13}.
        /// </summary>
        public static System.Drawing.Size Headline1_lbl_Size {
            get {
                object obj = ResourceManager.GetObject("Headline1_lbl.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int Headline1_lbl_TabIndex {
            get {
                object obj = ResourceManager.GetObject("Headline1_lbl.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to für einen Benutzer ein .
        /// </summary>
        public static string Headline1_lbl_Text {
            get {
                return ResourceManager.GetString("Headline1_lbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles Ok_btn_Anchor {
            get {
                object obj = ResourceManager.GetObject("Ok_btn.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=130,Y=129}.
        /// </summary>
        public static System.Drawing.Point Ok_btn_Location {
            get {
                object obj = ResourceManager.GetObject("Ok_btn.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=111, Height=23}.
        /// </summary>
        public static System.Drawing.Size Ok_btn_Size {
            get {
                object obj = ResourceManager.GetObject("Ok_btn.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int Ok_btn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("Ok_btn.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok_btn_Text {
            get {
                return ResourceManager.GetString("Ok_btn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles Password_lbl_Anchor {
            get {
                object obj = ResourceManager.GetObject("Password_lbl.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Password_lbl_AutoSize {
            get {
                object obj = ResourceManager.GetObject("Password_lbl.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=9,Y=87}.
        /// </summary>
        public static System.Drawing.Point Password_lbl_Location {
            get {
                object obj = ResourceManager.GetObject("Password_lbl.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=50, Height=13}.
        /// </summary>
        public static System.Drawing.Size Password_lbl_Size {
            get {
                object obj = ResourceManager.GetObject("Password_lbl.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int Password_lbl_TabIndex {
            get {
                object obj = ResourceManager.GetObject("Password_lbl.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string Password_lbl_Text {
            get {
                return ResourceManager.GetString("Password_lbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles Password_tb_Anchor {
            get {
                object obj = ResourceManager.GetObject("Password_tb.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=103}.
        /// </summary>
        public static System.Drawing.Point Password_tb_Location {
            get {
                object obj = ResourceManager.GetObject("Password_tb.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Char similar to •.
        /// </summary>
        public static char Password_tb_PasswordChar {
            get {
                object obj = ResourceManager.GetObject("Password_tb.PasswordChar", resourceCulture);
                return ((char)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=229, Height=20}.
        /// </summary>
        public static System.Drawing.Size Password_tb_Size {
            get {
                object obj = ResourceManager.GetObject("Password_tb.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int Password_tb_TabIndex {
            get {
                object obj = ResourceManager.GetObject("Password_tb.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles Username_lbl_Anchor {
            get {
                object obj = ResourceManager.GetObject("Username_lbl.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Username_lbl_AutoSize {
            get {
                object obj = ResourceManager.GetObject("Username_lbl.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=48}.
        /// </summary>
        public static System.Drawing.Point Username_lbl_Location {
            get {
                object obj = ResourceManager.GetObject("Username_lbl.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=13}.
        /// </summary>
        public static System.Drawing.Size Username_lbl_Size {
            get {
                object obj = ResourceManager.GetObject("Username_lbl.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int Username_lbl_TabIndex {
            get {
                object obj = ResourceManager.GetObject("Username_lbl.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        public static string Username_lbl_Text {
            get {
                return ResourceManager.GetString("Username_lbl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles Username_tb_Anchor {
            get {
                object obj = ResourceManager.GetObject("Username_tb.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=64}.
        /// </summary>
        public static System.Drawing.Point Username_tb_Location {
            get {
                object obj = ResourceManager.GetObject("Username_tb.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=229, Height=20}.
        /// </summary>
        public static System.Drawing.Size Username_tb_Size {
            get {
                object obj = ResourceManager.GetObject("Username_tb.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int Username_tb_TabIndex {
            get {
                object obj = ResourceManager.GetObject("Username_tb.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
